// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkfzqrzshlmjxwgdnkak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrZnpxcnpzaGxtanh3Z2Rua2FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMTE1NjUsImV4cCI6MjA3Mjc4NzU2NX0.m-KHeIgjU6CwEPcsqBNszJwpj-20yQeEHWI2GvO2pcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});